- hosts: localhost
  connection: local
  vars:
    image_url: "486909041565.dkr.ecr.ap-south-1.amazonaws.com/k8s-event-processor:latest"
    vault_path: "secret/aws-creds"

  tasks:
    - name: Vault secrets, Trivy scan, Docker pull, and Kubernetes deploy
      shell: |
        # Pull AWS creds from Vault
        export AWS_ACCESS_KEY_ID=$(vault kv get -field=AWS_ACCESS_KEY_ID {{ vault_path }})
        export AWS_SECRET_ACCESS_KEY=$(vault kv get -field=AWS_SECRET_ACCESS_KEY {{ vault_path }})

        # Pull Docker image
        docker pull {{ image_url }}

        # Run Trivy basic vulnerability scan
        trivy image --severity HIGH,CRITICAL {{ image_url }}
        if [ $? -ne 0 ]; then
          echo "Trivy scan detected HIGH/CRITICAL vulnerabilities. Deployment aborted!"
          exit 1
        fi

        # Apply Kubernetes manifests
        kubectl apply -f ../k8s/deployment.yaml
        kubectl apply -f ../k8s/cronjob-dlq-retry.yaml
        kubectl apply -f ../k8s/service.yaml
        kubectl apply -f ../k8s/file-processing-sa.yaml
      environment:
        KUBECONFIG: "{{ lookup('env','HOME') }}/.kube/config }}"
      register: deploy_result

    - debug:
        var: deploy_result.stdout
